// <auto-generated />
namespace PracEf2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class s2AddMany2Many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s2AddMany2Many));
        
        string IMigrationMetadata.Id
        {
            get { return "201904230711218_s2AddMany2Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
